version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: filp/whoops
    versions:
    - 2.12.0
  - dependency-name: friendsofphp/php-cs-fixer
    versions:
    - 2.18.5
  - dependency-name: laravel/framework
    versions:
    - 7.30.4
    - 8.22.1
  - dependency-name: symfony/polyfill-intl-normalizer
    versions:
    - 1.22.0
    - 1.22.1
  - dependency-name: symfony/polyfill-php72
    versions:
    - 1.22.0
    - 1.22.1
  - dependency-name: symfony/polyfill-php80
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-php73
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-intl-grapheme
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-intl-idn
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-mbstring
    versions:
    - 1.22.0
  - dependency-name: symfony/polyfill-iconv
    versions:
    - 1.22.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.5
    - 1.32.6
    - 1.32.7
  - dependency-name: sass-loader
    versions:
    - 10.1.1
