name: CodeStyle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpinsights:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Execute phpinsight
      run: php artisan insights
